apiVersion: v1
kind: Service
metadata:
  name: my-service-lb
spec:
  type: NodePort # Service for use multiple nodes
  selector:
    app: my-app
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 80
      targetPort: http 