apiVersion: v1
kind: Service
metadata:
  annotations:
    topology.kubernetes.io/zone: zn0
  labels:
    app: test-app
  name: test-np
  namespace: default
spec:
  type: NodePort 
  selector:
    app: test-app
  externalTrafficPolicy: Local    # Preserve the original IP address of the client connecting
  ports:
    - protocol: TCP
      nodePort: 31000 # May not work with multiple zones
      port: 80
      targetPort: http 