# optimize resources for day-night load cycle
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-down-job-zn0 # Reduce count of pods
spec:
  schedule: "0 20 * * *" # Every day at 8:00 PM
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure 
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest 
            imagePullPolicy: IfNotPresent
            args: 
              - scale
              - deployment
              - --replicas=1
              - test-deployment-zn0 
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-down-job-zn1 # Reduce count of pods
spec:
  schedule: "0 20 * * *" # Every day at 8:00 PM
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure 
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest 
            imagePullPolicy: IfNotPresent
            args: 
              - scale
              - deployment
              - --replicas=1
              - test-deployment-zn1 
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-up-job-zn0 # Increase count of pods
spec:
  schedule: "0 8 * * *" # Every day at 8:00 AM
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            args: 
              - scale
              - deployment
              - --replicas=5
              - test-deployment-zn0
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-up-job-zn1 # Increase count of pods
spec:
  schedule: "0 8 * * *" # Every day at 8:00 AM
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            imagePullPolicy: IfNotPresent
            args: 
              - scale
              - deployment
              - --replicas=5
              - test-deployment-zn1